[supabase]
url = "https://nyastptiarqqwgktxxrv.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55YXN0cHRpYXJxcXdna3R4eHJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc2NjQ0NzYsImV4cCI6MjEwMzI0MDQ3Nn0.f1EwOUoriOPBzLHMKY7oUuMMkCpCyNtcXXok69jDVg8"
